name: Types

#############################
# Start the job on all push #
#############################
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  types:
    name: Pyright Type Checking
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pipenv
          python --version; pip --version; pipenv --version
          pipenv requirements > requirements.txt
          pip install -r requirements.txt
      - name: Run pyright
        run: pyright 
